MyPortfolio/Controllers/DroneProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPortfolio.DAL;
using MyPortfolio.Models;

namespace MyPortfolio.Controllers
{
    public class DroneProjectsController : Controller
    {
        private MyPortfolioContext db = new MyPortfolioContext();

        // GET: DroneProjects
        public ActionResult Index()
        {
            return View(db.DroneProjects.ToList());
        }

        // GET: DroneProjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DroneProject droneProject = db.DroneProjects.Find(id);
            if (droneProject == null)
            {
                return HttpNotFound();
            }
            return View(droneProject);
        }

        // GET: DroneProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DroneProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectTitle,UploadDate")] DroneProject droneProject)
        {
            if (ModelState.IsValid)
            {
                db.DroneProjects.Add(droneProject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(droneProject);
        }

        // GET: DroneProjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DroneProject droneProject = db.DroneProjects.Find(id);
            if (droneProject == null)
            {
                return HttpNotFound();
            }
            return View(droneProject);
        }

        // POST: DroneProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjectTitle,UploadDate")] DroneProject droneProject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(droneProject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(droneProject);
        }

        // GET: DroneProjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DroneProject droneProject = db.DroneProjects.Find(id);
            if (droneProject == null)
            {
                return HttpNotFound();
            }
            return View(droneProject);
        }

        // POST: DroneProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DroneProject droneProject = db.DroneProjects.Find(id);
            db.DroneProjects.Remove(droneProject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPortfolio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyPortfolio/Controllers/ProgrammingProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPortfolio.DAL;
using MyPortfolio.Models;

namespace MyPortfolio.Controllers
{
    public class ProgrammingProjectsController : Controller
    {
        private MyPortfolioContext db = new MyPortfolioContext();

        // GET: ProgrammingProjects
        public ActionResult Index()
        {
            return View(db.ProgrammingProjects.ToList());
        }

        // GET: ProgrammingProjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProgrammingProject programmingProject = db.ProgrammingProjects.Find(id);
            if (programmingProject == null)
            {
                return HttpNotFound();
            }
            return View(programmingProject);
        }

        // GET: ProgrammingProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProgrammingProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectTitle,UploadDate")] ProgrammingProject programmingProject)
        {
            if (ModelState.IsValid)
            {
                db.ProgrammingProjects.Add(programmingProject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(programmingProject);
        }

        // GET: ProgrammingProjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProgrammingProject programmingProject = db.ProgrammingProjects.Find(id);
            if (programmingProject == null)
            {
                return HttpNotFound();
            }
            return View(programmingProject);
        }

        // POST: ProgrammingProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjectTitle,UploadDate")] ProgrammingProject programmingProject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(programmingProject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(programmingProject);
        }

        // GET: ProgrammingProjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProgrammingProject programmingProject = db.ProgrammingProjects.Find(id);
            if (programmingProject == null)
            {
                return HttpNotFound();
            }
            return View(programmingProject);
        }

        // POST: ProgrammingProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProgrammingProject programmingProject = db.ProgrammingProjects.Find(id);
            db.ProgrammingProjects.Remove(programmingProject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPortfolio/Controllers/ThreeDPrintingProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPortfolio.DAL;
using MyPortfolio.Models;

namespace MyPortfolio.Controllers
{
    public class ThreeDPrintingProjectsController : Controller
    {
        private MyPortfolioContext db = new MyPortfolioContext();

        // GET: ThreeDPrintingProjects
        public ActionResult Index()
        {
            return View(db.ThreeDPrintingProjects.ToList());
        }

        // GET: ThreeDPrintingProjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThreeDPrintingProject threeDPrintingProject = db.ThreeDPrintingProjects.Find(id);
            if (threeDPrintingProject == null)
            {
                return HttpNotFound();
            }
            return View(threeDPrintingProject);
        }

        // GET: ThreeDPrintingProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThreeDPrintingProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectTitle,UploadDate")] ThreeDPrintingProject threeDPrintingProject)
        {
            if (ModelState.IsValid)
            {
                db.ThreeDPrintingProjects.Add(threeDPrintingProject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(threeDPrintingProject);
        }

        // GET: ThreeDPrintingProjects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThreeDPrintingProject threeDPrintingProject = db.ThreeDPrintingProjects.Find(id);
            if (threeDPrintingProject == null)
            {
                return HttpNotFound();
            }
            return View(threeDPrintingProject);
        }

        // POST: ThreeDPrintingProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjectTitle,UploadDate")] ThreeDPrintingProject threeDPrintingProject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(threeDPrintingProject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(threeDPrintingProject);
        }

        // GET: ThreeDPrintingProjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThreeDPrintingProject threeDPrintingProject = db.ThreeDPrintingProjects.Find(id);
            if (threeDPrintingProject == null)
            {
                return HttpNotFound();
            }
            return View(threeDPrintingProject);
        }

        // POST: ThreeDPrintingProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThreeDPrintingProject threeDPrintingProject = db.ThreeDPrintingProjects.Find(id);
            db.ThreeDPrintingProjects.Remove(threeDPrintingProject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPortfolio/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Danny";
}

<div class="aboutIntro">
    <p><b>Short version...</b> A newbie developer, drone enthusiast, hobbyist maker (3D printing, arduino, RPi), with a non-technical background and skillset.</p>
</div>

<!--PRESENT-->
<h2 class="aboutHeader" data-toggle="collapse" data-target="#presentParagraph"><strong>The Present:</strong> Who am I?</h2>
<div id="presentParagraph" class="collapse">
    <p>
        <b>Ambitious self-funded MSc IT postgrad with Distinction; aiming to find a starting point for a software development career following five years working in a non-technical role in the business technology sector.</b>
    </p>
    <p>
        My primary language is C# using .NET framework, mostly self-taught. Proficient with HTML, CSS, JS, SQL and Git. Varying degrees of experience with other languages and frameworks including Java, C++, Python, Linux, NoSQL, Angular, Spring MVC Unit Testing, and ORMs such as Entity Framework and Dapper.
    </p>
    <p>
        Software projects and contributions include scrum development of a Java testing tool, collision avoidance drone implementation in C++, data analysis of EU referendum in HQL, cystic fibrosis mobile app using Angular2, and personal C# ASP.NET MVC5 web app projects.
    </p>
    <p>
        Previously a Project Manager/Campaign Director for Business Reporter in London, promoting business technology industries and clients to C-Suites via and The Telegraph Newspaper.
    </p>
    <p>
        Strong commercial experience (communication, marketing, sales, project management). Achievements included highest company average order value, first-ever six figure contract, meeting £230,000+ personal annual revenue targets, and strong repeating client base.
    </p>
    <p>
        Formerly, graduated with 2:1 Law, specialising in IT and company law.
    </p>
    <p>
        Hobbies include building drones, crashing drones, rebuilding drones, 3D printing, gym-ing and advancing my programming abilities. CV should demonstrate a unique mix of non-technical and technical skillsets.
    </p>
</div>
<br />
<!--EDUCATION AND EMPLOYMENT-->
<h2 class="aboutHeader" data-toggle="collapse" data-target="#educationAndEmployment"><strong>The Past:</strong> Education & Employment</h2>
<div id="educationAndEmployment" class="collapse">

    <h3 class="midAboutHeader">Education</h3>
    <br />
    <h4 id="uwe_msc_header" class="aboutSubHeader bg-danger text-white" data-toggle="collapse" data-target="#uwe_msc" style="padding: 5px; margin-bottom:5px;">
        MSc with Distinction, Information Technology 		(September 2016 – March 2017)
    </h4>
    <h6 class="location">University of West England</h6>

    <ul id="uwe_msc" class="collapse">
        <li><b>    Achieved distinction in all modules</b> including Software Engineering, Internet of Things and Linked Data, Information Security, Digital Design, Project Management, Professionalism & Governance, and Big Data. </li>
        <li>	Worked as <b>Scrum Developer for a Java Web Application</b>, using a Spring MVC framework, to build a software testing tool using X-Machine theory (called the ‘CompleX-Machine’).</li>
        <li><b>Led group work on Big Data, using Hortonworks to analyse open source data to learn about NoSQL, the available tools and produce a presentation on the EU Referendum. </b></li>
        <li><b>   Led group work on Information Security </b> addressing organisational culture concerns.</li>
        <li><b>Designed a prototype application using InVision and Angular2</b> called ‘Fyt’ aimed at helping cystic fibrosis sufferers better manage their health through exercise and challenges. </li>
        <li><b>	Dissertation focused on Autonomous Drone Technology </b> (download a copy – https://goo.gl/XM8KFq): </li>
        <ul>
            <li><b>Researched hobbyist drone technology</b> for dissertation i.e. how to build, how to program, communication protocols, typical hobbyist issues, state of the art solutions, electronics, sensors, aviation, regulation, machine learning…more than I can discuss here.
            <li>
                <b>Developed a basic collision avoidance prototype drone with C++</b>, using an ultrasonic sensor, Arduino and the Pixhawk flight controller (see filmed experiments https://goo.gl/zf1NLF)
            </li>
        </ul>
        <li><b>Led and delivered presentations </b> on virtual reality, big data analysis of the EU Referendum results, and a prototype software testing tool called the CompleX-Machine</li>
    </ul>

    <h4 class="aboutSubHeader bg-danger text-white" data-toggle="collapse" data-target="#staff_uni" style="padding: 5px; margin-bottom:5px;">
        LLB (Hons) 2:1, Law 					(September 2008 – August 2011)
    </h4>
    <h6 class="location">Staffordshire University</h6>
    <ul id="staff_uni" class="collapse">
        <li><b>Specialised in Information Technology</b>, Human Rights, Employment and Critical Company Law.</li>
        <li>Enjoyed mooting (mock court arguments).</li>
        <li>Developed strong <b>research, evidencing, negotiation, persuasion, advocacy, presentation and communication skills.</b></li>
    </ul>

    <h4 class="aboutSubHeader bg-danger text-white" data-toggle="collapse" data-target="#a_levels_and_gcse" style="padding: 5px; margin-bottom:5px;">
        A-Levels & GCSEs 					(September 2007 – August 2011)
    </h4>
    <h6 class="location">Sandbach School, Sandbach, Cheshire</h6>

    <ul id="a_levels_and_gcse" class="collapse">
        <li>A-Level: History: A, Politics: A, English Literature: B.</li>
        <li>AS-Level: Geography: A, Critical Thinking: A, General Studies: A.</li>
        <li>GCSE: A’s in English, Maths and Science, A’s and B’s across others.</li>
    </ul>

    <br />

    <h3 class="midAboutHeader">Employment</h3>
    <br />
    <h4 class="aboutSubHeader bg-danger text-white"
        data-toggle="collapse" data-target="#campaign_director" style="padding: 5px; margin-bottom:5px;">
        Campaign Director 					(September 2014 – August 2016)
    </h4>
    <h6 class="location">
        Lyonsdown, Business Reporter - www.lyonsdown.co.uk, www.business-reporter.co.uk, London
    </h6>
    <ul id="campaign_director" class="collapse">
        <li><b>Led development of integrated marketing campaigns created from new product offerings</b> which increased my average order value four-fold (digital articles, filmed interviews at The Telegraph Studios, C-Suite Briefings, B2B summits).</li>
        <li><b>Increased client repeats</b> – key clients included Interoute, Siemens, Sungard Availability Services, Capita IT Enterprise Services, Arvato.</li>
        <li><b>Collaborated with our editorial team </b>to shape Business Technology campaigns.</li>
        <li><b>Managed elements of delegate recruitment </b>on behalf of my clients.</li>
        <li><b>Conducted industry research on C-Suite technology issues</b> such as Digital Disruption, IT Transformation, Outsourcing, Information Security, Cloud Computing, IoT and Big Data.</li>
        <li><b>Developed strong business acumen;</b> learning about marketing (digital, events, print), sales, project management, learning from the business owners directly.</li>
    </ul>


    <h4 class="aboutSubHeader bg-danger text-white" data-toggle="collapse" data-target="#project_manager" style="padding: 5px; margin-bottom:5px;">
        Project Manager 					(September 2011 – August 2014)
    </h4>
    <h6 class="location">
        Lyonsdown, Business Reporter – www.lyonsdown.co.uk, www.business-reporter.co.uk, London
    </h6>
    <ul id="project_manager" class="collapse">
        <li>Produced and gathered sponsorship for <b>B2B Business Technology reports, distributed in The Telegraph Newspaper, The Guardian and City AM.</b></li>
        <li><b>Recruited OTE sponsorship of circa £50,000 per report, annual target circa £200,000.</b></li>
        <li>Shaped campaigns with industry research for our target audience (typically C-Suite readers) and target sponsors (technology brands) to bridge a gap in communication.</li>
        <li><b>Achieved a record month, including the first six-figure contract</b> in the company’s history, as the youngest Project Manager - £113,995.</li>
    </ul>

</div>

<br />
<!--THE FUTURE-->

<h2 class="aboutHeader" data-toggle="collapse" data-target="#theFuture" ><strong>The Future:</strong> My Ambitions</h2>
<div id="theFuture" class="collapse">
    <p>
        Currently <b>seeking an opportunity to deepen and professionalise my coding and technical abilities</b>. Whether my own venture, in a leadership role, or has lead developer, I would love to be part of a disruptive project in the future.
    </p>

    <p>Personally, I think drones, virtual reality, 3D printing, robotics and AI will be the big disruptions coming soonest! But there's plenty of tech disruption to deal with in the meantime.</p>

</div>

<script>

    $(document).ready(function () {
        

        $(".aboutHeader").click(function () {
            $(".in").removeClass("in").addClass("collapse");

            //TODO: Need to turn highlight off
            this.style.backgroundColor = "#f4424e";
            
        })
    })
</script>

MyPortfolio/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyPortfolio/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


@*<div class="jumbotron">
    <h1><em>"Learning through repeated failure..."</em></h1>
    <p class="lead">My name's Danny Zapp Dunn, I like coding things, making things, and long walks on the beach...</p>
    <p>I've just completed my IT MSc, and I'm keen to start work as an entry-level developer</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo; <span class="glyphicon glyphicon-adjust"></span></a></p>
</div>*@

<div class="videoOuter">
    <div class="videoMiddle">
        <div class="videoInner">
            <video class="embed-responsive-item" autoplay muted loop>
                <source src="~/Content/videos/AsboSquadV2.mp4" type="video/mp4">
            </video>
            <p class="centered">
                <span class="videoTextHeader">My name's Danny Zapp Dunn, I like coding things, making things, and long walks on the beach...</span>
                <br />
    <br/>
            
                <span class="videoTextSub">I've just completed my IT MSc, and I'm keen to start work as an entry-level developer</span>
            </p>
            
        </div>
   
    </div>
</div>

<br />

<div class="row" >
    <div class="col-md-4">
        <div class="homePageImageContainer">
            <img src="~/Content/images/Programming.jpg" />
        </div>
        <h2>Programming Projects</h2>
        <p>
            Around a year ago, I couldn't code at all. Since then, I've acquired skills in the basic scripting languages (HTML, CSS/Bootstrap, JavaScript/JQuery, SQL)
            alongside programming languages like Java, C++ and C#. Check out my projects thus far...
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Programming Projects &raquo;"), "Index", "ProgrammingProjects", new { }, new { @class = "btn btn-danger" })</p>
    </div>
    <div class="col-md-4">
        <div class="homePageImageContainer">
            <img src="~/Content/images/Drone.jpg" />
        </div>
        <h2>Drone Projects</h2>
        <p>
            Around a year ago, I knew nothing about electronics, avaiation or drones. Since then, it's become an addictively expensive hobby.
            Have a gander at my various tony whoops, racing quads, autonomous drones and flight footage...
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Drone Projects &raquo;"), "Index", "DroneProjects", new { }, new { @class = "btn btn-danger" })</p>
    </div>
    <div class="col-md-4">
        <div class="homePageImageContainer">
            <img src="~/Content/images/3Dprinter.jpg" />
        </div>
        <h2>3D Printing Projects</h2>
        <p>
            Around a year ago, I knew nothing about 3D printing. At the start of this year, I built my first Anet A8 - a cheap but effective option with a massive
            community behind it. Take a peruse through my printing journey...
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("3D Printing Projects &raquo;"), "Index", "ThreeDPrintingProjects", new { }, new { @class = "btn btn-danger" })</p>
    </div>
</div>